# Generated by Django 5.2.7 on 2025-11-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='chef',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='day',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
