# Generated by Django 5.2.7 on 2025-11-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_fooditem_chef_fooditem_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='session',
            field=models.CharField(max_length=20),
        ),
    ]
